// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhJ9v9FdoM8jOdyvO3NCdBxbgvaSzvXIw',
    appId: '1:599727555123:web:83f5e1455ab6525e719946',
    messagingSenderId: '599727555123',
    projectId: 'fir-project-f8b2c',
    authDomain: 'fir-project-f8b2c.firebaseapp.com',
    storageBucket: 'fir-project-f8b2c.firebasestorage.app',
    measurementId: 'G-P46DDFJM5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf19WR80xv8b_a-V-DiAR2uCs5Cl8O-hY',
    appId: '1:599727555123:android:f60c81e0b1b6a81c719946',
    messagingSenderId: '599727555123',
    projectId: 'fir-project-f8b2c',
    storageBucket: 'fir-project-f8b2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmvK4EWyAuFM9Ns2DsYAMeA7ExrpAsMxQ',
    appId: '1:599727555123:ios:d94d2466d8b33261719946',
    messagingSenderId: '599727555123',
    projectId: 'fir-project-f8b2c',
    storageBucket: 'fir-project-f8b2c.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );
}
